### ISSUE TITLE
CI error about wire version

### ISSUE THREAD

**Issue by letmaik** [jumaffre/cimetrics#125]
> pymongo.errors.ConfigurationError: Server at cdb-ms-prod-eastus1-fd3.documents.azure.com:10255 reports wire version 2, but this version of PyMongo requires at least 6 (MongoDB 3.6).

**Comment by achamayou** [comment]
We had this on the other instance, there's a button under features that migrates to a newer version of the protocol and fixes it.

**Comment by achamayou** [comment]
In flight now, will update ticket when complete.

**Comment by achamayou** [comment]
Complete now, but the connection string needs swapping.

**Comment by jumaffre** [comment]
Connection string updated and CI pipeline is now green on GH Actions too: https://github.com/jumaffre/cimetrics/pull/124
