### ISSUE TITLE
Support for GitHub Actions CI

### ISSUE THREAD

**Issue by achamayou** [jumaffre/cimetrics#38]

**Comment by letmaik** [comment]
Probably this repo should switch to Actions as well, looking at https://github.com/jumaffre/cimetrics/pull/72#issuecomment-579970110.

**Comment by achamayou** [comment]
As long as we use DevOps in other projects (which is the foreseeable future), we still want to support that too, so I think we just add a GitHub CI?

**Comment by letmaik** [comment]
Fair point, was thinking about that. Although having two cimetrics runs per commit may be a bit confusing. Configuration would also be more complex and not be a simple sample anymore, which this repo conveniently is as well. Needs more thought I think.

**Comment by achamayou** [comment]
Yes, I agree with all your points, and I'm not sure what the right solution is. I suppose we could have a look at what people like codecov do and take inspiration from them, since they must have the same problems.

In any case, I don't think we ought to de-prioritise support for Pipelines any time soon.

**Comment by achamayou** [comment]
I suspect we can get away with working out a scheme where CI systems somehow tag/label the comment they create/update. So for each PR there would be two plot comments, one for Actions and one for Pipelines, each updated by their respective job.

**Comment by achamayou** [comment]
Annoyingly, making an Env for Github Actions is not straightforward because:

- There's no way to detect an action run is for a PR
- There's no way to tell what the target branch for a PR

Less critically, but still annoying, there's no human-friendly YYYYMMDD.N build number like in Pipelines, the run id seems to be a uuid while the run number is an auto incrementing integer.

I can think of some crude hacks that would work for simple repos (configure a single target branch per repo for example), but I'll do some more research first in the hope of finding something better. If anyone has ideas, I'd love to hear them.

Sources:
https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
Test run under https://github.com/jumaffre/cimetrics/pull/94/checks?check_run_id=703792019

**Comment by achamayou** [comment]
Found https://github.com/jwalton/gh-find-current-pr but that needs an auth token. Ugh.

**Comment by letmaik** [comment]
GITHUB_TOKEN is always available, this should just work.

**Comment by achamayou** [comment]
@letmaik ah yes, indeed. It's annoying to have to configure this as a dependency though.

Since it's just a single request, I guess we may as well do it ourselves.
