### ISSUE TITLE
Edit GitHub PR comments instead of posting a new one

### ISSUE THREAD

**Issue by jumaffre** [jumaffre/cimetrics#54]
As it stands, every time a PR-build that uses cimetrics is run, a new report/comment is posted on the GitHub PR. This is nice as it shows the historical evolution of the metrics since the PR was opened. However, it is very verbose.

Instead, we should edit the original comment with a new report for every additional build on the PR (instead of posting a new comment). See https://developer.github.com/v3/issues/comments/#edit-a-comment.

**Comment by achamayou** [comment]
Can't seem to get the edit API to work unfortunately, I just get 404s the whole time.
