### ISSUE TITLE
Align subplot title all the way to the left to free up some title space

### ISSUE THREAD

**Issue by achamayou** [jumaffre/cimetrics#59]

**Comment by achamayou** [comment]
I wonder if the solution to that isn't to move the yaxis legend to the right instead. The % change would have to move, perhaps to the left of the marker, but that doesn't seem too bad (it might obscure recent data points, that's the only problem), or perhaps above it.

**Comment by jumaffre** [comment]
I strongly think the % change should not move to the area where the points are plotted as the % change is the first key information one wants to (very quickly) read when looking at a report. We can try a few options in a separate PR but I would prefer moving the title all the way to the left.

**Comment by achamayou** [comment]
Another option might be to move the %change in the top righ corner (aligned with the title). I'll experiment and you and @letmaik can review :)
