### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by achamayou** [jumaffre/cimetrics#98]

**Comment by ghost** [comment]
v0.3.15@[849 aka 20230214.10](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=849&view=results) vs main ewma over 29 builds from [2](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=2&view=results) to [848](https://dev.azure.com/jumaffre/metrics-devops/_build/results?buildId=848&view=results)
<details>
  <summary>Click to see table</summary>
  
  main
  
  |   build_id | build_number   |   Throughput (tx/s) ^ |   Latency (ms) |   Peak working set size (GB) |   Accuracy (%) ^ |   Error rate (%) |   Memory fragmentation (%) |   CPU usage (%) |   New metric (U) |
|-----------:|:---------------|----------------------:|---------------:|-----------------------------:|-----------------:|-----------------:|---------------------------:|----------------:|-----------------:|
|          2 | 0000.0         |               49042.8 |            9.5 |                         51.5 |           0.7175 |           0.0575 |                    0.02125 |          0.3125 |            132.5 |
|        725 | 20211130.3     |               51282   |           11   |                         49   |           0.69   |           0.05   |                    0.021   |          0.32   |            158   |
|        733 | 20211207.4     |               46509   |           11   |                         55   |           0.69   |           0.06   |                    0.018   |          0.29   |            163   |
|        734 | 20211207.5     |               50987   |           11   |                         52   |           0.68   |           0.04   |                    0.021   |          0.29   |            108   |
|        747 | 20211230.12    |               47349   |            9   |                         46   |           0.72   |           0.06   |                    0.021   |          0.31   |            197   |
|        749 | 20211230.14    |               51543   |           11   |                         49   |           0.72   |           0.04   |                    0.018   |          0.31   |            135   |
|        773 | 20211230.38    |               46436   |           10   |                         49   |           0.68   |           0.04   |                    0.02    |          0.28   |            192   |
|        785 | 20211230.50    |               51363   |           11   |                         53   |           0.72   |           0.05   |                    0.021   |          0.3    |            170   |
|        787 | 20211230.52    |               46324   |           10   |                         47   |           0.7    |           0.04   |                    0.022   |          0.3    |            108   |
|        788 | 20211230.53    |               47610   |           11   |                         54   |           0.68   |           0.04   |                    0.022   |          0.31   |            147   |
|        791 | 20211230.56    |               50696   |           11   |                         54   |           0.69   |           0.04   |                    0.021   |          0.29   |            144   |
|        792 | 20211230.57    |               48522   |           11   |                         54   |           0.71   |           0.04   |                    0.021   |          0.32   |            149   |
|        793 | 20211231.1     |               50878   |           11   |                         51   |           0.69   |           0.06   |                    0.018   |          0.31   |            135   |
|        794 | 20211231.2     |               46777   |           11   |                         47   |           0.68   |           0.04   |                    0.021   |          0.31   |            127   |
|        802 | 20211231.10    |               48500   |           11   |                         51   |           0.69   |           0.05   |                    0.02    |          0.32   |            120   |
|        805 | 20211231.13    |               47604   |            9   |                         46   |           0.73   |           0.06   |                    0.018   |          0.28   |            120   |
|        807 | 20211231.15    |               50668   |           10   |                         48   |           0.69   |           0.04   |                    0.021   |          0.31   |            122   |
|        821 | 20211231.29    |               51821   |            9   |                         51   |           0.73   |           0.04   |                    0.019   |          0.29   |            191   |
|        823 | 20211231.31    |               50426   |           10   |                         50   |           0.71   |           0.06   |                    0.019   |          0.31   |            154   |
|        824 | 20211231.32    |               50190   |           11   |                         54   |           0.68   |           0.05   |                    0.022   |          0.3    |            183   |
|        829 | 20211231.37    |               51701   |           10   |                         50   |           0.73   |           0.05   |                    0.022   |          0.28   |            139   |
|        831 | 20220428.1     |               46173   |           10   |                         53   |           0.68   |           0.04   |                    0.021   |          0.3    |            173   |
|        832 | 20221021.1     |               47161   |           10   |                         50   |           0.7    |           0.06   |                    0.019   |          0.28   |            135   |
|        833 | 20221114.1     |               47547   |           10   |                         48   |           0.68   |           0.05   |                    0.02    |          0.28   |            159   |
|        835 | 20221114.3     |               48964   |           11   |                         52   |           0.71   |           0.06   |                    0.021   |          0.31   |            134   |
|        839 | 20221114.7     |               48308   |            9   |                         47   |           0.71   |           0.05   |                    0.021   |          0.31   |            150   |
|        840 | 20230214.1     |               49764   |           11   |                         55   |           0.72   |           0.06   |                    0.021   |          0.32   |            155   |
|        847 | 20230214.8     |               49036   |            9   |                         46   |           0.72   |           0.06   |                    0.019   |          0.3    |            106   |
|        848 | 20230214.9     |               47604   |           10   |                         53   |           0.71   |           0.05   |                    0.021   |          0.31   |            125   |
  
  
</details>

![images](https://plots.z33.web.core.windows.net/plot-jumaffre-cimetrics-98.png)
